data:
  mysql:
    max_idle_conns: 50
    source_name: "root:123456@tcp(127.0.0.1:3306)/devops?parseTime=true&charset=utf8&loc=Local"
  mongodb:
    username: "root"
    password: "123456"
  redis:
    username: "root"
    password: "123456"

http: "0.0.0.0:8008"
log_path: "./"