http:
  host: 127.0.0.1
  port: 8999
  secret: a7e6a5b690b7e190869a25b7187e3202741ba6205b9c8eda2a35f0e6a26982c39bd91f6b443c275d135d95a9f8b803a7215111a7f25ddf38f03ac16823025a22
logger:
  directory: ./logs
  formatter: '[%(levelname)s]%(asctime)s[%(filename)s:%(lineno)s][%(name)s]: %(message)s'
debug: true
dataSource:
  MySQL:
    host: 127.0.0.1
    port: 3306
    username: root
    password: root
    database: vivy
    option: '?parseTime=true&charset=utf8mb4&loc=Local'
    maxIdle: 10
    maxOpen: 100
    showSql: true
    showExecTime: true
