data_source:
  mysql:
    host: "127.0.0.1"
    port: 3306
    username: "root"
    password: "root"
    database: "vivy"
    options: "?parseTime=true&charset=utf8&loc=Local"
    driver_name: "mysql"
    show_sql: true
    show_exec_time: false
    max_idle: 50
    max_open: 200
  mongodb:
    host: "127.0.0.1"
    port: 27017
    username: "root"
    password: "root"
  redis:
    host: "127.0.0.1"
    port: 6379
    username: "root"
    password: "root"
service:
  http:
    host: "0.0.0.0"
    port: 8088
logger:
  path: "./logs"
debug: true
