data_source:
  mysql:
    host: "127.0.0.1"
    port: 3306
    username: "root"
    password: "root"
    database: "vivy"
    options: "?parseTime=true&charset=utf8&loc=Local"
    max_idle_conns: 50
  mongodb:
    host: "127.0.0.1"
    port: 27017
    username: "root"
    password: "123456"
  redis:
    host: "127.0.0.1"
    port: 6379
    username: "root"
    password: "123456"

service:
  http:
    host: "0.0.0.0"
    port: 8088

logger:
  path: "./"

debug: true
