captcha:
  img-height: 60
  img-width: 120
  key-long: 5
casbin:
  model-path: --TODO--
cors:
  mode: --TODO--
  whitelist: []
data-source:
  mongodb:
    host: localhost
    password: <password>
    port: 27017
    username: <username>
  mysql:
    database: vivy
    host: localhost
    log-mode: --TODO--
    log-zap: true
    max-idle: 20
    max-open: 100
    option: parseTime=true&charset=utf8mb4&loc=Local
    password: root
    port: 3306
    show-exec-time: false
    show-sql: false
    username: root
  redis:
    address: localhost:6379
    max-idle: 10
    password: root
    protocol: tcp
dev:
  debug: false
service:
  host: 127.0.0.1
  port: 9088
  session-secret: 1234567890abcdef
  static-path: ./web
  template-html: true
zap:
  directory: ./logs
  encode-level: --TODO--
  format: --TODO--
  level: info
  log-in-console: true
  prefix: ""
  showline: true
  stacktrace-key: --TODO--
